name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi! Welcome to the PythOS Pro repository. Thanks for filing a new issue!"
        pr-message: "Hi! This must be your first pull request on the PythOS Pro repository! How fun!"
